/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as GrokRouteImport } from './routes/grok'
import { Route as MatchRouteImport } from './routes/match'
import { Route as MoreRouteImport } from './routes/more'
import { Route as TowRouteImport } from './routes/tow'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as ValueRouteImport } from './routes/value'
import { Route as VinRouteImport } from './routes/vin'
import { Route as RvSlugRouteImport } from './routes/rv/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const GrokRoute = GrokRouteImport.update({
  id: '/grok',
  path: '/grok',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const TowRoute = TowRouteImport.update({
  id: '/tow',
  path: '/tow',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ValueRoute = ValueRouteImport.update({
  id: '/value',
  path: '/value',
  getParentRoute: () => rootRouteImport,
} as any)
const VinRoute = VinRouteImport.update({
  id: '/vin',
  path: '/vin',
  getParentRoute: () => rootRouteImport,
} as any)
const RvSlugRoute = RvSlugRouteImport.update({
  id: '/rv/$slug',
  path: '/rv/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/finance': typeof FinanceRoute
  '/garage': typeof GarageRoute
  '/grok': typeof GrokRoute
  '/match': typeof MatchRoute
  '/more': typeof MoreRoute
  '/tow': typeof TowRoute
  '/trips': typeof TripsRoute
  '/value': typeof ValueRoute
  '/vin': typeof VinRoute
  '/rv/$slug': typeof RvSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/finance': typeof FinanceRoute
  '/garage': typeof GarageRoute
  '/grok': typeof GrokRoute
  '/match': typeof MatchRoute
  '/more': typeof MoreRoute
  '/tow': typeof TowRoute
  '/trips': typeof TripsRoute
  '/value': typeof ValueRoute
  '/vin': typeof VinRoute
  '/rv/$slug': typeof RvSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/finance': typeof FinanceRoute
  '/garage': typeof GarageRoute
  '/grok': typeof GrokRoute
  '/match': typeof MatchRoute
  '/more': typeof MoreRoute
  '/tow': typeof TowRoute
  '/trips': typeof TripsRoute
  '/value': typeof ValueRoute
  '/vin': typeof VinRoute
  '/rv/$slug': typeof RvSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compare'
    | '/finance'
    | '/garage'
    | '/grok'
    | '/match'
    | '/more'
    | '/tow'
    | '/trips'
    | '/value'
    | '/vin'
    | '/rv/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compare'
    | '/finance'
    | '/garage'
    | '/grok'
    | '/match'
    | '/more'
    | '/tow'
    | '/trips'
    | '/value'
    | '/vin'
    | '/rv/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compare'
    | '/finance'
    | '/garage'
    | '/grok'
    | '/match'
    | '/more'
    | '/tow'
    | '/trips'
    | '/value'
    | '/vin'
    | '/rv/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompareRoute: typeof CompareRoute
  FinanceRoute: typeof FinanceRoute
  GarageRoute: typeof GarageRoute
  GrokRoute: typeof GrokRoute
  MatchRoute: typeof MatchRoute
  MoreRoute: typeof MoreRoute
  TowRoute: typeof TowRoute
  TripsRoute: typeof TripsRoute
  ValueRoute: typeof ValueRoute
  VinRoute: typeof VinRoute
  RvSlugRoute: typeof RvSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grok': {
      id: '/grok'
      path: '/grok'
      fullPath: '/grok'
      preLoaderRoute: typeof GrokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tow': {
      id: '/tow'
      path: '/tow'
      fullPath: '/tow'
      preLoaderRoute: typeof TowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/value': {
      id: '/value'
      path: '/value'
      fullPath: '/value'
      preLoaderRoute: typeof ValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vin': {
      id: '/vin'
      path: '/vin'
      fullPath: '/vin'
      preLoaderRoute: typeof VinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rv/$slug': {
      id: '/rv/$slug'
      path: '/rv/$slug'
      fullPath: '/rv/$slug'
      preLoaderRoute: typeof RvSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompareRoute: CompareRoute,
  FinanceRoute: FinanceRoute,
  GarageRoute: GarageRoute,
  GrokRoute: GrokRoute,
  MatchRoute: MatchRoute,
  MoreRoute: MoreRoute,
  TowRoute: TowRoute,
  TripsRoute: TripsRoute,
  ValueRoute: ValueRoute,
  VinRoute: VinRoute,
  RvSlugRoute: RvSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
